print("How old are you? ", end=' ')
age = input()
print("How tall are you? ", end=' ')
height = input()
print("How much do you weigh?", end=' ')
weight = input()
print("What is your favorite color?", end=' ')
color = input()
print('Enter a number:')
x = int(input())
print('Enter another number:')
y = int(input())
total = x + y
times = x * y

print(f"So, you are {age} years old, {height} tall, and {weight} pounds.")
print("My, what a clever creature you are!")
print(f"I like {color} too!")
print("This has been fun, have a good one!")
print(str(x) + ' + ' + str(y) + ' = ' + str(total))
print(str(x) + ' x ' + str(y) + ' = ' + str(times))